export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex h-screen overflow-auto">
      <div className="w-full md:w-1/2 flex justify-center items-center flex-col">
        {children}
      </div>
      <div className="w-1/2 hidden md:block" style={{ background: "url(/images/sydney-cbd-from-ferry-boat2.jpg)", backgroundSize: "cover" }}>
      </div>
    </div>
  )
}
